const maintenanceRequests = [
  {
    id: 1,
    message:
      "The kitchen sink is leaking and causing water to pool under the cabinet.",
    status: "pending",
    dateSubmitted: "2025-04-30T09:15:00Z",
    tenant: {
      id: "T001",
      name: "Maria Gomez",
      phone: "+1 (555) 123-4567",
      email: "maria.gomez@example.com",
      gender: "Female",
      nationalId: "XA1234567",
      image: "/images/tenants/maria.jpg",
      unit: "Apt 2B",
      property: "Sunset Apartments",
    },
  },
  {
    id: 2,
    message: "The heater is not working properly in the bedroom.",
    status: "done",
    dateSubmitted: "2025-04-28T14:20:00Z",
    tenant: {
      id: "T002",
      name: "James Lee",
      phone: "+1 (555) 987-6543",
      email: "james.lee@example.com",
      gender: "Male",
      nationalId: "XB9876543",
      image: "/images/tenants/james.jpg",
      unit: "Unit 5A",
      property: "Elmwood Complex",
    },
  },
  {
    id: 3,
    message: "There’s mold forming on the bathroom ceiling.",
    status: "pending",
    dateSubmitted: "2025-04-29T11:45:00Z",
    tenant: {
      id: "T003",
      name: "Amina Yusuf",
      phone: "+1 (555) 555-1212",
      email: "amina.yusuf@example.com",
      gender: "Female",
      nationalId: "XC3456789",
      image: "/images/tenants/amina.jpg",
      unit: "Flat 3C",
      property: "Lakeside View",
    },
  },
  {
    id: 4,
    message: "The living room light switch sparks when used.",
    status: "pending",
    dateSubmitted: "2025-04-27T17:10:00Z",
    tenant: {
      id: "T004",
      name: "Omar Khan",
      phone: "+1 (555) 222-3344",
      email: "omar.khan@example.com",
      gender: "Male",
      nationalId: "XD5678901",
      image: "/images/tenants/omar.jpg",
      unit: "Unit 1A",
      property: "Greenwood Heights",
    },
  },
  {
    id: 5,
    message: "The balcony door doesn't lock properly.",
    status: "done",
    dateSubmitted: "2025-04-26T08:30:00Z",
    tenant: {
      id: "T005",
      name: "Emily Chen",
      phone: "+1 (555) 333-7788",
      email: "emily.chen@example.com",
      gender: "Female",
      nationalId: "XE6789012",
      image: "/images/tenants/emily.jpg",
      unit: "Apt 4D",
      property: "Maple Residences",
    },
  },
  {
    id: 6,
    message: "There's a strong odor coming from the garbage disposal area.",
    status: "pending",
    dateSubmitted: "2025-04-30T12:05:00Z",
    tenant: {
      id: "T006",
      name: "Luis Martinez",
      phone: "+1 (555) 444-8899",
      email: "luis.martinez@example.com",
      gender: "Male",
      nationalId: "XF7890123",
      image: "/images/tenants/luis.jpg",
      unit: "Unit 6C",
      property: "Harbor Point",
    },
  },
];

export default maintenanceRequests;
